steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', 
            '-t', 
            'gcr.io/eternal-seeker-374308/trainer', 
            '-f', 
            'trainer.dockerfile', 
            '.']

   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 
            'gcr.io/eternal-seeker-374308/trainer']
