#config.yaml
hyperparameters:
        batch_size: 100
        lr: 1e-3
        epochs: 20
        seed: 42
        cuda: True
        train_data_path: '../../../data/processed/training_data.pickle'
        model_out_path: '../../../models/'