#config.yaml
hyperparameters:
        batch_size: 100
        lr: 1e-3
        epochs: 100
        seed: 2
        cuda: False
        limit_train_batches: 0.2
        patience: 20
        train_data_path: '/gcs/dtumlops2023/data/dummy/training_data.pickle'
        val_data_path: '/gcs/dtumlops2023/data/dummy/validation_data.pickle'
        model_out_path: 'models/'
        num_workers: 8