#config.yaml
hyperparameters:
        batch_size: 10
        lr: 1e-3
        epochs: 20
        seed: 42
        cuda: False
        limit_train_batches: 0.1
        patience: 10
        train_data_path: '/gcs/dtumlops2023/data/dummy/training_data.pickle'
        val_data_path: '/gcs/dtumlops2023/data/dummy/validation_data.pickle'
        model_out_path: 'models/'